#!/bin/bash
#############################
# les directives Slurm vont ici:

# Your job name (displayed by the queue)
#SBATCH -J kawsh

# walltime (hh:mm::ss)
#SBATCH -t 10:10:00

# Specify the number of nodes(nodes=) and the number of cores per nodes(tasks-pernode=) to be used
#SBATCH --ntasks 10

# change working directory
# SBATCH --chdir=.

# fin des directives PBS
#############################

# modules cleaning
#module purge
module add mpi/intel/2018.5.274

# useful informations to print
echo "#############################" 
echo "User:" $USER
echo "Date:" `date`
echo "Host:" `hostname`
echo "Directory:" `pwd`
echo "SLURM_JOBID:" $SLURM_JOBID
echo "SLURM_SUBMIT_DIR:" $SLURM_SUBMIT_DIR
echo "SLURM_JOB_NODELIST:" $SLURM_JOB_NODELIST
echo "SLURM_NAME:" $SLURM_JOB_NAME
echo "#############################" 

#############################

# What you actually want to launch
options="-t $temp -prefix $prefix"
if (( $(echo " $h > 0" | bc) )) ; then options="$options -h $h" ; fi
if (( $(echo " $f > 0" | bc) )) ; then options="$options -f $f" ; fi
if (( $(echo " $l > 0" | bc) )) ; then options="$options -ly $l" ; fi
echo $options

time mpirun  ${prefix}/stargate $options
# all done
