#!/bin/sh

# directives PBS vont ici:

# Your job name (displayed by the queue)
#PBS -N kawsh

# Specify the working directory
#PBS -d .

# walltime (hh:mm::ss)
#PBS -l walltime=11:30:00

# Specify the number of nodes(nodes=) and the number of cores per nodes(ppn=) to be used
#PBS -l nodes=1:ppn=8

# fin des directives PBS
#############################

# modules cleaning
module purge
module add torque
module load gcc/5.1.0
module add intel-mpi torque-intel-mpi

# useful informations to print
echo "#############################" 
echo "User:" $USER
echo "Date:" `date`
echo "Host:" `hostname`
echo "Directory:" `pwd`
echo "PBS_JOBID:" $PBS_JOBID
echo "PBS_O_WORKDIR:" $PBS_O_WORKDIR
echo "PBS_NODEFILE: " `cat $PBS_NODEFILE | uniq`
echo "#############################" 

#############################

# What you actually want to launch
str=''
if [ -z ${temp+x} -o $t -eq 1 ]; then echo ''; else str="$str -t ${temp}" ; fi
if [ -z ${prefix+x} ]; then echo ''; else str="$str -prefix ${prefix}" ; fi
if [ -z ${h+x} -o $h -eq 0 ]; then echo ''; else str="$str -h ${h}" ; fi
if [ -z ${f+x} -o $f -eq 0 ]; then echo ''; else str="$str -f ${f}" ; fi
if [ -z ${l+x} -o $l -eq 0 ]; then echo ''; else str="$str -ly ${l}" ; fi

NUMPROC=`cat $PBS_NODEFILE | wc -l`
I_MPI_FABRICS=shm:tmi mpirun -np $NUMPROC ${prefix}/stargate $str 
# all done
