#!/bin/bash
#############################
# les directives Slurm vont ici:

# Your job name (displayed by the queue)
#SBATCH -J kawsh

# walltime (hh:mm::ss)
#SBATCH -t 4:10:00

# Specify the number of nodes(nodes=) and the number of cores per nodes(tasks-pernode=) to be used
#SBATCH --ntasks 1

# change working directory
# SBATCH --chdir=.

# fin des directives PBS
#############################

# modules cleaning
#module add openmpi/2.1.6
module load mpi/intel/2018.5.274
#module load mpi/mvapich2/2.3.1          
#ompi_info --param mpi all --level 9

# useful informations to print
echo "#############################" 
echo "User:" $USER
echo "Date:" `date`
echo "Host:" `hostname`
echo "Directory:" `pwd`
echo "SLURM_JOBID:" $SLURM_JOBID
echo "SLURM_SUBMIT_DIR:" $SLURM_SUBMIT_DIR
echo "SLURM_JOB_NODELIST:" $SLURM_JOB_NODELIST
echo "SLURM_NAME:" $SLURM_JOB_NAME
echo "#############################" 

#############################

# What you actually want to launch
options="-t $temp -prefix $prefix"
if (( $(echo " $m > 0" | bc) )) ; then options="$options -m $h" ; fi
if (( $(echo " $temp >= 0" | bc) )) ; then options="$options -t $temp" ; fi
echo $options

time mpirun ${prefix}/stargate $options 
#time mpirun valgrind ${prefix}/stargate $options --track-origins=yes --leak-check=full
# all done
