#!/bin/bash

##################################################
########### Compilation et prefixage #############
##################################################
shopt -s extglob #pour permettre de passer de 0.23500000 à 0.235
module load gcc openmpi/gcc
module load gcc/5.1.0
module unload gcc/stable

while :; do
    case $1 in
        -d ) flags="-pedantic -Wall -Wextra -Wold-style-cast -Woverloaded-virtual -Wfloat-equal -Wwrite-strings -Wpointer-arith -Wcast-qual -Wcast-align  -Wshadow -Weffc++ -Wredundant-decls -Wdouble-promotion -Winit-self -Wswitch-default -Wswitch-enum -Wundef -Wlogical-op -Winline -g";;
        -g ) flags="-gdwarf-3" ;;
        * ) break ;;
    esac
    shift 1
done


LC_ALL="en_US.UTF-8"


exec_prefix="."
data_prefix="test"

g++ -std=c++11 -Wall -I/usr/include/ -c $exec_prefix/main.cpp -o $exec_prefix/main.o -fopenmp
g++ -std=c++11 -L/usr/local/lib64/ -o $data_prefix/stargate  $exec_prefix/main.o -lgsl -lgslcblas -lm -fopenmp
 $flags
