#!/bin/bash

##################################################
########### Compilation et prefixage #############
##################################################
shopt -s extglob #pour permettre de passer de 0.23500000 à 0.235
module load mpi/intel/2019.3.199
LC_ALL="en_US.UTF-8"


prefix=$(pwd)
exec_prefix=$prefix/
#data_prefix=/scratch/pgersberg/symmetrique
data_prefix=$prefix/test
debut_nom=${PWD##*/} ; debut_nom=${debut_nom:0:2}${data_prefix: -2}


mkdir -p $data_prefix
mpicc -std=c++11 -O3 -g -Wall -c $exec_prefix/main.cpp -o $exec_prefix/main.o -I ~/libeigen
if [ $? -ne 0 ] ; then exit 1 ; fi
mpicc -std=c++11 -O3 -g -o $data_prefix/stargate  $exec_prefix/main.o -lm -lstdc++ -I ~/libeigen
if [ $? -ne 0 ] ; then exit 1 ; fi
rm $exec_prefix/main.o
cp $exec_prefix/main.cpp $data_prefix

