#!/bin/bash
export LC_ALL="en_US.UTF-8"

containsElement () {
  local e
  for e in "${@:2}"; do [[ "$e" == "$1" ]] && return 1; done
  return 0
}


#fichier : $1

####CE CODE MARCHE !!! ##
declare -a temp=()

rm tri
#tac $1 > tri
tac $1 > tri
while read line; do
	regexp='^[0-9]+\.?[0-9]*'
	[[ $line =~ $regexp ]]
	var=${BASH_REMATCH[0]}
	if containsElement "$var" "${temp[@]}" ; then
		temp=("${temp[@]}" "$var" )
	fi
done < <(cat tri)

for nb in ${temp[@]}; do
	trouve=0
	while read line; do
		[[ $line =~ $regexp ]]
		var=${BASH_REMATCH[0]}
		if [[ "$var" == "$nb" ]]  ; then
			if [[ "$trouve" == 0 ]]; then 
				trouve=1; 
				echo $line >> cou
			else
				break
			fi;
		fi
	done < <(cat tri)
done


cat cou | sort -n -k1n,1n > 'tri'
rm cou
mv tri $1.tri
