  INTEGER, PARAMETER :: LDX = 129, NX1 = 128, NX2 = 256
  INTEGER, PARAMETER :: LDY = 64,  NY1 =  64, NY2 = 256
  REAL(KIND=8), DIMENSION(LDX, NX2)        :: X
  COMPLEX(KIND=8), DIMENSION(LDY, NY2)     :: Y
  REAL(KIND=8), DIMENSION(512*NX2)         :: WORK
  REAL(KIND=8), DIMENSION(100+2*(NX1+NX2)) :: TABLE
  INTEGER                                  :: IRC
  CHARACTER(LEN=80)                        :: MESSAGE

  ! ... (Definition de X)

  CALL JMSETERREUR(.false.)
  CALL SCFFT2D(0, 128, 256, 1.d0, X, 129, Y, 64, TABLE, WORK, 0)
  CALL JMGETCODE(IRC)
  IF (IRC .NE. 0) THEN
    CALL JMGETMESSAGE(IRC,MESSAGE)
    PRINT *,'Code',IRC,', ',TRIM(MESSAGE)
    CALL HANDLER()
  END IF
  CALL SCFFT2D(1, 128, 256, 1.d0, X, 129, Y, 64, TABLE, WORK, 0)

  ! ... (Impression de Y)

END

SUBROUTINE HANDLER()
  STOP
END SUBROUTINE HANDLER
