#!/bin/sh

# directives PBS vont ici:

# Your job name (displayed by the queue)
#PBS -N openmp

# Specify the working directory
#PBS -d .

# walltime (hh:mm::ss)
#PBS -l walltime=0:02:20

# Specify the number of nodes(nodes=) and the number of cores per nodes(ppn=) to be used
#PBS -l nodes=1:ppn=8

# fin des directives PBS
#############################

# modules cleaning
module purge
module add torque
module load gcc/5.1.0/

# useful informations to print
echo "#############################" 
echo "User:" $USER
echo "Date:" `date`
echo "Host:" `hostname`
echo "Directory:" `pwd`
echo "PBS_JOBID:" $PBS_JOBID
echo "PBS_O_WORKDIR:" $PBS_O_WORKDIR
echo "PBS_NODEFILE: " `cat $PBS_NODEFILE | uniq`
echo "#############################" 

#############################

# What you actually want to launch
make mono
./prod_mat_mono.exe
# all done
