#!/bin/sh

# directives PBS vont ici:

# Your job name (displayed by the queue)
#PBS -N rm_symmetrique

# Specify the working directory
#PBS -d .

# walltime (hh:mm::ss)
#PBS -l walltime=2:00:00

# Specify the number of nodes(nodes=) and the number of cores per nodes(ppn=) to be used
#PBS -l nodes=1:ppn=1

# fin des directives PBS
#############################

# modules cleaning
module purge
module add torque
module load gcc/5.1.0/

# useful informations to print
echo "#############################" 
echo "User:" $USER
echo "Date:" `date`
echo "Host:" `hostname`
echo "Directory:" `pwd`
echo "PBS_JOBID:" $PBS_JOBID
echo "PBS_O_WORKDIR:" $PBS_O_WORKDIR
echo "PBS_NODEFILE: " `cat $PBS_NODEFILE | uniq`
echo "#############################" 

#############################

# What you actually want to launch
cd /home/pgersberg/Kaw-mag/bien
perl -e 'for(<*>){((stat)[9]<(unlink))}'
# all done
