#!/bin/bash
exec_prefix="."
mkdir test
data_prefix="test"
g++ -std=c++11 -Wall -I/usr/include/ -c $exec_prefix/main.cpp -o $exec_prefix/main.o
g++ -std=c++11 -Wall -I/usr/include/ -c $exec_prefix/math.cpp -o $exec_prefix/math.o
g++ -std=c++11 -Wall -I/usr/include/ -c $exec_prefix/dynamique.cpp -o $exec_prefix/dynamique.o
g++ -std=c++11 -L/usr/local/lib64/ -o $data_prefix/stargate  $exec_prefix/main.o $exec_prefix/math.o $exec_prefix/dynamique.o -lgsl -lgslcblas -lm
rm *.o



